// Code generated by "stringer -type=PacketType -output=string.go"; DO NOT EDIT.

package ospf3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HelloPacket-1]
	_ = x[DatabaseDescriptionPacket-2]
	_ = x[LinkStateRequestPacket-3]
	_ = x[LinkStateUpdatePacket-4]
	_ = x[LinkStateAcknowledgementPacket-5]
}

const _PacketType_name = "HelloPacketDatabaseDescriptionPacketLinkStateRequestPacketLinkStateUpdatePacketLinkStateAcknowledgementPacket"

var _PacketType_index = [...]uint8{0, 11, 36, 58, 79, 109}

func (i PacketType) String() string {
	i -= 1
	if i >= PacketType(len(_PacketType_index)-1) {
		return "PacketType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
