name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run unprivileged tests
      run: go test -race ./...

    - name: Set up veth pair for privileged tests
      run: sudo ip link add vethospf0 type veth peer name vethospf1

    - name: Bring up vethospf0
      run: sudo ip link set up vethospf0

    - name: Bring up vethospf1
      run: sudo ip link set up vethospf1

    - name: Build test binary
      run: go test -c -race .

    - name: Run privileged tests
      run: sudo ./ospf3.test
